-- List of controller inputs from here
-- https://docs.fivem.net/docs/game-references/controls/
-- 

-- Credit to Menyoo for some of this list:
-- Repo: https://github.com/itsjustcurtis/MenyooSP/tree/main
-- Enum list: https://github.com/itsjustcurtis/MenyooSP/blob/main/Solution/source/Scripting/enums.h

ControllerInput = {
    INPUT_FRONTEND_DOWN = 187,
	INPUT_FRONTEND_UP = 188,
	INPUT_FRONTEND_LEFT = 189,
	INPUT_FRONTEND_RIGHT = 190,
	INPUT_FRONTEND_RDOWN = 191,
	INPUT_FRONTEND_RUP = 192,
	INPUT_FRONTEND_RLEFT = 193,
	INPUT_FRONTEND_RRIGHT = 194,
	INPUT_FRONTEND_AXIS_X = 195,
	INPUT_FRONTEND_AXIS_Y = 196,
	INPUT_FRONTEND_RIGHT_AXIS_X = 197,
	INPUT_FRONTEND_RIGHT_AXIS_Y = 198,
	INPUT_FRONTEND_PAUSE = 199,
	INPUT_FRONTEND_PAUSE_ALTERNATE = 200,
	INPUT_FRONTEND_ACCEPT = 201,
	INPUT_FRONTEND_CANCEL = 202,
	INPUT_FRONTEND_X = 203,
	INPUT_FRONTEND_Y = 204,
	INPUT_FRONTEND_LB = 205,
	INPUT_FRONTEND_RB = 206,
	INPUT_FRONTEND_LT = 207,
	INPUT_FRONTEND_RT = 208,
	INPUT_FRONTEND_LS = 209,
	INPUT_FRONTEND_RS = 210,
	INPUT_FRONTEND_LEADERBOARD = 211,
	INPUT_FRONTEND_SOCIAL_CLUB = 212,
	INPUT_FRONTEND_SOCIAL_CLUB_SECONDARY = 213,
	INPUT_FRONTEND_DELETE = 214,
	INPUT_FRONTEND_ENDSCREEN_ACCEPT = 215,
	INPUT_FRONTEND_ENDSCREEN_EXPAND = 216,
	INPUT_FRONTEND_SELECT = 217,
}

HudComponent = {
    WantedStars = 1,
	WeaponIcon = 2,
	Cash = 3,
	MpCash = 4,
	MpMessage = 5,
	VehicleName = 6,
	AreaName = 7,
	--Unused = 8,
	StreetName = 9,
	HelpText = 10,
	FloatingHelpText1 = 11,
	FloatingHelpText2 = 12,
	CashChange = 13,
	Reticle = 14,
	SubtitleText = 15,
	RadioStationsWheel = 16,
	Saving = 17,
	GamingStreamUnusde = 18,
	WeaponWheel = 19,
	WeaponWheelStats = 20,
	DrugsPurse01 = 21,
	DrugsPurse02 = 22,
	DrugsPurse03 = 23,
	DrugsPurse04 = 24,
	MpTagCashFromBank = 25,
	MpTagPackages = 26,
	MpTagCuffKeys = 27,
	MpTagDownloadData = 28,
	MpTagIfPedFollowing = 29,
	MpTagKeyCard = 30,
	MpTagRandomObject = 31,
	MpTagRemoteControl = 32,
	MpTagCashFromSafe = 33,
	MpTagWeaponsPackage = 34,
	MpTagKeys = 35,
	MpVehicle = 36,
	MpVehicleHeli = 37,
	MpVehiclePlane = 38,
	PlayerSwitchAlert = 39,
	MpRankBar = 40,
	DirectorMode = 41,
	ReplayController = 42,
	ReplayMouse = 43,
	ReplayHeader = 44,
	ReplayOptions = 45,
	ReplayHelpText = 46,
	ReplayMiscText = 47,
	ReplayTopLine = 48,
	ReplayBottomLine = 49,
	ReplayLeftBar = 50,
	ReplayTimer = 51,
	MAX_SCRIPTED_HUD_COMPONENTS = 141
}

ParachuteState = {
    Normal = -1,
	WearingOnBack = 0,
	ParachuteOpening = 1,
	ParachuteOpen = 2,
	FallingToDoom = 3
}


-- https://wiki.rage.mp/wiki/Weather
WeatherType = {
    -- Unknown = -1,
	ExtraSunny = 0,
	Clear = 1,
	Clouds = 2,
	Smog = 3,
	Foggy = 4,
	Overcast = 5,
	Rain = 6,
	Thunder = 7,
	Clearing = 8,
	Neutral = 9,
	Snow = 10,
	Blizzard = 11,
	SnowLight = 12,
	XMAS = 13,
	Halloween = 14,
	SNOW_HALLOWEEN = 15,
	RAIN_HALLOWEEN = 16
}

-- https://docs.fivem.net/natives/?_0xE3AD2BDBAEE269AC
ExplosionTypes = {
	DONTCARE = -1,
	GRENADE = 0,
	GRENADELAUNCHER = 1,
	STICKYBOMB = 2,
	MOLOTOV = 3,
	ROCKET = 4,
	TANKSHELL = 5,
	HI_OCTANE = 6,
	CAR = 7,
	PLANE = 8,
	PETROL_PUMP = 9,
	BIKE = 10,
	DIR_STEAM = 11,
	DIR_FLAME = 12,
	DIR_WATER_HYDRANT = 13,
	DIR_GAS_CANISTER = 14,
	BOAT = 15,
	SHIP_DESTROY = 16,
	TRUCK = 17,
	BULLET = 18,
	SMOKE_GRENADE_LAUNCHER = 19,
	SMOKE_GRENADE = 20,
	BZGAS = 21,
	FLARE = 22,
	GAS_CANISTER = 23,
	EXTINGUISHER = 24,
	PROGRAMMABLEAR = 25,
	TRAIN = 26,
	BARREL = 27,
	PROPANE = 28,
	BLIMP = 29,
	DIR_FLAME_EXPLODE = 30,
	TANKER = 31,
	PLANE_ROCKET = 32,
	VEHICLE_BULLET = 33,
	GAS_TANK = 34,
	BIRD_CRAP = 35,
	RAILGUN = 36,
	BLIMP2 = 37,
	FIREWORK = 38,
	SNOWBALL = 39,
	PROXMINE = 40,
	VALKYRIE_CANNON = 41,
	AIR_DEFENCE = 42,
	PIPEBOMB = 43,
	VEHICLEMINE = 44,
	EXPLOSIVEAMMO = 45,
	APCSHELL = 46,
	BOMB_CLUSTER = 47,
	BOMB_GAS = 48,
	BOMB_INCENDIARY = 49,
	BOMB_STANDARD = 50,
	TORPEDO = 51,
	TORPEDO_UNDERWATER = 52,
	BOMBUSHKA_CANNON = 53,
	BOMB_CLUSTER_SECONDARY = 54,
	HUNTER_BARRAGE = 55,
	HUNTER_CANNON = 56,
	ROGUE_CANNON = 57,
	MINE_UNDERWATER = 58,
	ORBITAL_CANNON = 59,
	BOMB_STANDARD_WIDE = 60,
	EXPLOSIVEAMMO_SHOTGUN = 61,
	OPPRESSOR2_CANNON = 62,
	MORTAR_KINETIC = 63,
	VEHICLEMINE_KINETIC = 64,
	VEHICLEMINE_EMP = 65,
	VEHICLEMINE_SPIKE = 66,
	VEHICLEMINE_SLICK = 67,
	VEHICLEMINE_TAR = 68,
	SCRIPT_DRONE = 69,
	RAYGUN = 70,
	BURIEDMINE = 71,
	SCRIPT_MISSILE = 72,
	RCTANK_ROCKET = 73,
	BOMB_WATER = 74,
	BOMB_WATER_SECONDARY = 75,
	MINE_CNCSPIKE = 76,
	BZGAS_MK2 = 77,
	FLASHGRENADE = 78,
	STUNGRENADE = 79,
	CNC_KINETICRAM = 80,
	SCRIPT_MISSILE_LARGE = 81,
	SUBMARINE_BIG = 82,
	EMPLAUNCHER_EMP = 83
}

-- ScreenEffect = {
--     	SwitchShortMichaelIn,
-- 		SwitchHUDOut,
-- 		SwitchHUDMichaelIn,
-- 		MinigameTransitionIn,
-- 		SwitchShortFranklinMid,
-- 		SwitchSceneMichael,
-- 		SwitchShortNeutralIn,
-- 		MP_Celeb_Win_Out,
-- 		MP_Celeb_Lose_Out,
-- 		MinigameEndNeutral,
-- 		MP_Celeb_Win,
-- 		MP_Celeb_Lose,
-- 		MP_race_crash,
-- 		RaceTurbo,
-- 		FocusOut,
-- 		FocusIn,
-- 		MinigameTransitionOut,
-- 		MP_job_load,
-- 		MenuMGOut,
-- 		MenuMGIn,
-- 		DeathFailMPIn,
-- 		SuccessFranklin,
-- 		SuccessTrevor,
-- 		SuccessMichael,
-- 		DeathFailOut,
-- 		MinigameEndMichael,
-- 		MinigameEndFranklin,
-- 		MinigameEndTrevor,
-- 		SwitchSceneTrevor,
-- 		SwitchShortFranklinIn,
-- 		SwitchShortMichaelMid,
-- 		SuccessNeutral,
-- 		MP_corona_switch,
-- 		SwitchOpenFranklin,
-- 		SwitchHUDMichaelOut,
-- 		SwitchHUDFranklinOut,
-- 		SwitchHUDTrevorOut,
-- 		SwitchHUDFranklinIn,
-- 		SwitchHUDTrevorIn,
-- 		SwitchHUDIn,
-- 		ChopVision,
-- 		SniperOverlay,
-- 		DrugsDrivingOut,
-- 		DMT_flight,
-- 		DMT_flight_intro,
-- 		DrugsDrivingIn,
-- 		MP_intro_logo,
-- 		ExplosionJosh3,
-- 		Dont_tazeme_bro
-- }